version: '3.8'

services:
  app:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
    restart: always
    ports:
      - "80:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://mysql:3306/ttarum
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=secret
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.3
    restart: always
    environment:
      - MYSQL_DATABASE=ttarum
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data: