version: '3.8'

services:
  app:
    build: .
    platform: linux/amd64
    restart: always
    ports:
      - "80:8080"
    env_file:
      - /home/ec2-user/.env
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.3
    restart: always
    environment:
      - MYSQL_DATABASE=ttarum
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data: