name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ttarum-back
  ECR_REPOSITORY: ttarum
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ec2-user
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2
        run: |
          KEY_FILE=$(mktemp)
          echo "$SSH_PRIVATE_KEY" > "$KEY_FILE"
          chmod 600 "$KEY_FILE"
          touch hi.txt
          rm "$KEY_FILE"